DROP DATABASE IF EXISTS DB_TCCGRUPO8;
CREATE DATABASE DB_TCCGRUPO8;

USE DB_TCCGRUPO8;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100) NOT NULL
	, EMAIL VARCHAR(100) NOT NULL
	, SENHA VARCHAR(45) NOT NULL
);


select * from usuario;