DROP DATABASE IF EXISTS ChatDB;
CREATE DATABASE ChatDB;

USE ChatDB;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100) NOT NULL
	, EMAIL VARCHAR(100) NOT NULL
	, SENHA VARCHAR(45) NOT NULL
);


select * from usuario;